#!/bin/bash

red='\033[1;31m'
green='\033[1;32m'
cyan='\033[1;36m'
NC='\033[0m' # No Color

####
## Install Node Modules for Gulp
####
if [ ! -d "node_modules" ]; then
	sudo npm link del
	sudo npm link gulp
	sudo npm link gulp-autoprefixer
	sudo npm link gulp-cdnizer
	sudo npm link gulp-imagemin
	sudo npm link gulp-jshint
	sudo npm link gulp-livereload
	sudo npm link gulp-load-plugins
	sudo npm link gulp-minify-css
	sudo npm link gulp-minify-html
	sudo npm link gulp-replace
	sudo npm link gulp-rev
	sudo npm link gulp-sass
	sudo npm link gulp-svgmin
	sudo npm link gulp-uglify
	sudo npm link gulp-usemin
	sudo npm link gulp-util
	sudo npm link svgo

	sudo chown ryanschie: ./node_modules
	sudo chown -R ryanschie: ./node_modules/*

	echo -e "${green}Added Node Modules${NC}"
fi

####
## Install API Vendor
####
if [ -d "api" ]; then

	cd api

	if [ ! -d "vendor" ]; then
		composer install
		echo -e "${green}Installed API Vendor Files${NC}"
	fi

	sudo chown ryanschie: ./vendor
	sudo chown -R ryanschie: ./vendor/*
	cd ../
fi

####
## Rename Title
####
if [ $1 ]; then
	input=`echo $1 | gsed -E "s/(^|-)([a-z])/\ \u\2/g"`

	sed -e "s/angular-boilerplate/$1/g" \
	 -e "s/\"description\":\ \"My\ Angular\ Boilerplate\"/\"description\":\ \"Project$input\"/g" \
	 package.json > package.json.tmp && mv package.json.tmp package.json

	sed -e "s/angular-boilerplate/$1/g" \
	 -e "s/\"description\":\ \"My\ Angular\ Boilerplate\"/\"description\":\ \"Project$input\"/g" \
	 bower.json > bower.json.tmp && mv bower.json.tmp bower.json

	sed -e "s/Angular Boilerplate/Project$input/g" \
	 README.md > README.md.tmp && mv README.md.tmp README.md

	sed -e "s/\<title\>Angular Boilerplate\<\/title\>/\<title\>Project$input\<\/title\>/g" \
	 dev/index.html > dev/index.html.tmp && mv dev/index.html.tmp dev/index.html

	 echo -e "${green}Renamed Project${NC}"
fi


